<?php
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2010 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/
$vardefs = array (
  'fields' => 
  array (
    'contact_id_c' => 
    array (
      'required' => false,
      'name' => 'contact_id_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 36,
    ),
    'the_client' => 
    array (
      'required' => '1',
      'source' => 'non-db',
      'name' => 'the_client',
      'vname' => 'LBL_THE_CLIENT',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
      'id_name' => 'contact_id_c',
      'ext2' => 'Contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'transaction_subject' => 
    array (
      'required' => false,
      'name' => 'transaction_subject',
      'vname' => 'LBL_TRANSACTION_SUBJECT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'transaction_subject_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'offered_date_of_closing_of_the' => 
    array (
      'required' => false,
      'name' => 'offered_date_of_closing_of_the',
      'vname' => 'LBL_OFFERED_DATE_OF_CLOSING_OF_THE',
      'type' => 'date',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
    ),
    'offered_sum_of_transaction' => 
    array (
      'required' => false,
      'name' => 'offered_sum_of_transaction',
      'vname' => 'LBL_OFFERED_SUM_OF_TRANSACTION',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'currency_id' => 
    array (
      'required' => false,
      'name' => 'currency_id',
      'vname' => 'LBL_CURRENCY',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 36,
      'studio' => 'visible',
      'function' => 
      array (
        'name' => 'getCurrencyDropDown',
        'returns' => 'html',
      ),
    ),
    'the_offered_sum_of_the_commiss' => 
    array (
      'required' => false,
      'name' => 'the_offered_sum_of_the_commiss',
      'vname' => 'LBL_THE_OFFERED_SUM_OF_THE_COMMISS',
      'type' => 'float',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '18',
      'precision' => '0',
    ),
    'sale_stage' => 
    array (
      'required' => false,
      'name' => 'sale_stage',
      'vname' => 'LBL_SALE_STAGE',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'sale_stage_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'operation_type' => 
    array (
      'required' => '1',
      'name' => 'operation_type',
      'vname' => 'LBL_OPERATION_TYPE',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'operation_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'the_address_city' => 
    array (
      'required' => false,
      'name' => 'the_address_city',
      'vname' => 'LBL_THE_ADDRESS_CITY',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
    ),
    'the_address_state' => 
    array (
      'required' => false,
      'name' => 'the_address_state',
      'vname' => 'LBL_THE_ADDRESS_STATE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
    ),
    'the_address_postalcode' => 
    array (
      'required' => false,
      'name' => 'the_address_postalcode',
      'vname' => 'LBL_THE_ADDRESS_POSTALCODE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 20,
    ),
    'the_address_country' => 
    array (
      'required' => false,
      'name' => 'the_address_country',
      'vname' => 'LBL_THE_ADDRESS_COUNTRY',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
    ),
    'the_address' => 
    array (
      'required' => false,
      'name' => 'the_address',
      'vname' => 'LBL_THE_ADDRESS',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '25',
    ),
    'territorial_arrangement' => 
    array (
      'required' => false,
      'name' => 'territorial_arrangement',
      'vname' => 'LBL_TERRITORIAL_ARRANGEMENT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'territorial_arrangement_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'district' => 
    array (
      'required' => false,
      'name' => 'district',
      'vname' => 'LBL_DISTRICT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'district_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'distance_from_mkad_from' => 
    array (
      'required' => false,
      'name' => 'distance_from_mkad_from',
      'vname' => 'LBL_DISTANCE_FROM_MKAD_FROM',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'distance_from_mkad_to' => 
    array (
      'required' => false,
      'name' => 'distance_from_mkad_to',
      'vname' => 'LBL_DISTANCE_FROM_MKAD_TO',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'highway' => 
    array (
      'required' => false,
      'name' => 'highway',
      'vname' => 'LBL_HIGHWAY',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'highway_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'to_be_in' => 
    array (
      'required' => false,
      'name' => 'to_be_in',
      'vname' => 'LBL_TO_BE_IN',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'is_in_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'the_area_from' => 
    array (
      'required' => false,
      'name' => 'the_area_from',
      'vname' => 'LBL_THE_AREA_FROM',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'the_area_to' => 
    array (
      'required' => false,
      'name' => 'the_area_to',
      'vname' => 'LBL_THE_AREA_TO',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'the_area_of_a_site_from' => 
    array (
      'required' => false,
      'name' => 'the_area_of_a_site_from',
      'vname' => 'LBL_THE_AREA_OF_A_SITE_FROM',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'the_area_of_a_site_to' => 
    array (
      'required' => false,
      'name' => 'the_area_of_a_site_to',
      'vname' => 'LBL_THE_AREA_OF_A_SITE_TO',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'toponymic_area' => 
    array (
      'required' => false,
      'name' => 'toponymic_area',
      'vname' => 'LBL_TOPONYMIC_AREA',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'toponymic_area_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'assumptions_on_the_area' => 
    array (
      'required' => false,
      'name' => 'assumptions_on_the_area',
      'vname' => 'LBL_ASSUMPTIONS_ON_THE_AREA',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'furnish_condition' => 
    array (
      'required' => false,
      'name' => 'furnish_condition',
      'vname' => 'LBL_FURNISH_CONDITION',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'furnish_condition_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'project_cost_entirely_from' => 
    array (
      'required' => false,
      'name' => 'project_cost_entirely_from',
      'vname' => 'LBL_PROJECT_COST_ENTIRELY_FROM',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'project_cost_entirely_to' => 
    array (
      'required' => false,
      'name' => 'project_cost_entirely_to',
      'vname' => 'LBL_PROJECT_COST_ENTIRELY_TO',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'cost_for_sq_m_from' => 
    array (
      'required' => false,
      'name' => 'cost_for_sq_m_from',
      'vname' => 'LBL_COST_FOR_SQ_M_FROM',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'cost_for_sq_m_to' => 
    array (
      'required' => false,
      'name' => 'cost_for_sq_m_to',
      'vname' => 'LBL_COST_FOR_SQ_M_TO',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'cost_for_a_hundred_part_from' => 
    array (
      'required' => false,
      'name' => 'cost_for_a_hundred_part_from',
      'vname' => 'LBL_COST_FOR_A_HUNDRED_PART_FROM',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'cost_for_a_hundred_part_to' => 
    array (
      'required' => false,
      'name' => 'cost_for_a_hundred_part_to',
      'vname' => 'LBL_COST_FOR_A_HUNDRED_PART_TO',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'cost_of_rent_of_object_entirel' => 
    array (
      'required' => false,
      'name' => 'cost_of_rent_of_object_entirel',
      'vname' => 'LBL_COST_OF_RENT_OF_OBJECT_ENTIREL',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'cost_rent_of_obj_entir_month_t' => 
    array (
      'required' => false,
      'name' => 'cost_rent_of_obj_entir_month_t',
      'vname' => 'LBL_COST_RENT_OF_OBJ_ENTIR_MONTH_T',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'rent_cost_for_sqm_year_from' => 
    array (
      'required' => false,
      'name' => 'rent_cost_for_sqm_year_from',
      'vname' => 'LBL_RENT_COST_FOR_SQM_YEAR_FROM',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'rent_cost_for_sqm_year_to' => 
    array (
      'required' => false,
      'name' => 'rent_cost_for_sqm_year_to',
      'vname' => 'LBL_RENT_COST_FOR_SQM_YEAR_TO',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'condition_' => 
    array (
      'required' => false,
      'name' => 'condition_',
      'vname' => 'LBL_CONDITION_',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'condition_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'd1_interest_id_c' => 
    array (
      'required' => false,
      'name' => 'd1_interest_id_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 36,
    ),
    'interest_source' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'interest_source',
      'vname' => 'LBL_INTEREST_SOURCE',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
      'id_name' => 'd1_interest_id_c',
      'ext2' => 'd1_interest',
      'module' => 'd1_interest',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'estimation' => 
    array (
      'required' => false,
      'name' => 'estimation',
      'vname' => 'LBL_ESTIMATION',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'estimation_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'priority' => 
    array (
      'required' => false,
      'name' => 'priority',
      'vname' => 'LBL_PRIORITY',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'priority_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'description_2' => 
    array (
      'required' => false,
      'name' => 'description_2',
      'vname' => 'LBL_DESCRIPTION_2',
      'type' => 'text',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'studio' => 'visible',
    ),
    'transaction_stage' => 
    array (
      'required' => false,
      'name' => 'transaction_stage',
      'vname' => 'LBL_TRANSACTION_STAGE',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'transaction_stage_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'the_income' => 
    array (
      'required' => false,
      'name' => 'the_income',
      'vname' => 'LBL_THE_INCOME',
      'type' => 'radioenum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'the_income_list',
      'studio' => 'visible',
      'dbType' => 'enum',
      'separator' => '<br>',
    ),
    'the_prospective_income' => 
    array (
      'required' => false,
      'name' => 'the_prospective_income',
      'vname' => 'LBL_THE_PROSPECTIVE_INCOME',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'probability' => 
    array (
      'required' => false,
      'name' => 'probability',
      'vname' => 'LBL_PROBABILITY',
      'type' => 'float',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '18',
      'precision' => '0',
    ),
    'd1_company_id_c' => 
    array (
      'required' => false,
      'name' => 'd1_company_id_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 36,
    ),
    'in_company' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'in_company',
      'vname' => 'LBL_IN_COMPANY',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
      'id_name' => 'd1_company_id_c',
      'ext2' => 'd1_Company',
      'module' => 'd1_Company',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
  ),
  'relationships' => 
  array (
  ),
);
?>
