<?php
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2010 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/
$vardefs = array (
  'fields' => 
  array (
    'transaction_subject' => 
    array (
      'required' => '1',
      'name' => 'transaction_subject',
      'vname' => 'LBL_TRANSACTION_SUBJECT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'transaction_subject_0',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'operation_type' => 
    array (
      'required' => '1',
      'name' => 'operation_type',
      'vname' => 'LBL_OPERATION_TYPE',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'operation_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'is_in' => 
    array (
      'required' => false,
      'name' => 'is_in',
      'vname' => 'LBL_IS_IN',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'is_in_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'office_class' => 
    array (
      'required' => '1',
      'name' => 'office_class',
      'vname' => 'LBL_OFFICE_CLASS',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'office_class_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'category_of_objects_of_the_tra' => 
    array (
      'required' => false,
      'name' => 'category_of_objects_of_the_tra',
      'vname' => 'LBL_CATEGORY_OF_OBJECTS_OF_THE_TRA',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'category_of_objects_of_the_tra_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'd1_interest_id_c' => 
    array (
      'required' => false,
      'name' => 'd1_interest_id_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 36,
    ),
    'interest' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'interest',
      'vname' => 'LBL_INTEREST',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
      'id_name' => 'd1_interest_id_c',
      'ext2' => 'd1_interest',
      'module' => 'd1_interest',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'condition_' => 
    array (
      'required' => false,
      'name' => 'condition_',
      'vname' => 'LBL_CONDITION_',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'condition_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'district' => 
    array (
      'required' => '1',
      'name' => 'district',
      'vname' => 'LBL_DISTRICT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'district_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'toponymic_area' => 
    array (
      'required' => '1',
      'name' => 'toponymic_area',
      'vname' => 'LBL_TOPONYMIC_AREA',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'toponymic_area_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'territorial_arrangement' => 
    array (
      'required' => '1',
      'name' => 'territorial_arrangement',
      'vname' => 'LBL_TERRITORIAL_ARRANGEMENT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'territorial_arrangement_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'distance_to_the_underground' => 
    array (
      'required' => false,
      'name' => 'distance_to_the_underground',
      'vname' => 'LBL_DISTANCE_TO_THE_UNDERGROUND',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'highway' => 
    array (
      'required' => false,
      'name' => 'highway',
      'vname' => 'LBL_HIGHWAY',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'highway_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'distance_from_mkad' => 
    array (
      'required' => false,
      'name' => 'distance_from_mkad',
      'vname' => 'LBL_DISTANCE_FROM_MKAD',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'the_address_city' => 
    array (
      'required' => false,
      'name' => 'the_address_city',
      'vname' => 'LBL_THE_ADDRESS_CITY',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
    ),
    'the_address_state' => 
    array (
      'required' => false,
      'name' => 'the_address_state',
      'vname' => 'LBL_THE_ADDRESS_STATE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
    ),
    'the_address_postalcode' => 
    array (
      'required' => false,
      'name' => 'the_address_postalcode',
      'vname' => 'LBL_THE_ADDRESS_POSTALCODE',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 20,
    ),
    'the_address_country' => 
    array (
      'required' => false,
      'name' => 'the_address_country',
      'vname' => 'LBL_THE_ADDRESS_COUNTRY',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
    ),
    'the_address' => 
    array (
      'required' => false,
      'name' => 'the_address',
      'vname' => 'LBL_THE_ADDRESS',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '25',
    ),
    'object_from' => 
    array (
      'required' => false,
      'name' => 'object_from',
      'vname' => 'LBL_OBJECT_FROM',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'object_from_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'contact_id_c' => 
    array (
      'required' => false,
      'name' => 'contact_id_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 36,
    ),
    'contact_physical_person' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'contact_physical_person',
      'vname' => 'LBL_CONTACT_PHYSICAL_PERSON',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
      'id_name' => 'contact_id_c',
      'ext2' => 'Contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'contact_id1_c' => 
    array (
      'required' => false,
      'name' => 'contact_id1_c',
      'vname' => '',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 36,
    ),
    'contact_legal_person' => 
    array (
      'required' => false,
      'source' => 'non-db',
      'name' => 'contact_legal_person',
      'vname' => 'LBL_CONTACT_LEGAL_PERSON',
      'type' => 'relate',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
      'id_name' => 'contact_id1_c',
      'ext2' => 'Contacts',
      'module' => 'Contacts',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    ),
    'currency_id' => 
    array (
      'required' => false,
      'name' => 'currency_id',
      'vname' => 'LBL_CURRENCY',
      'type' => 'id',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 36,
      'studio' => 'visible',
      'function' => 
      array (
        'name' => 'getCurrencyDropDown',
        'returns' => 'html',
      ),
    ),
    'c_u_equally' => 
    array (
      'required' => false,
      'name' => 'c_u_equally',
      'vname' => 'LBL_C_U_EQUALLY',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'sale_cost_for_sq_m' => 
    array (
      'required' => false,
      'name' => 'sale_cost_for_sq_m',
      'vname' => 'LBL_SALE_COST_FOR_SQ_M',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'sale_cost_for_sq_m_in_roubles' => 
    array (
      'required' => false,
      'name' => 'sale_cost_for_sq_m_in_roubles',
      'vname' => 'LBL_SALE_COST_FOR_SQ_M_IN_ROUBLES',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'sale_cost_for_a_hundred_part' => 
    array (
      'required' => false,
      'name' => 'sale_cost_for_a_hundred_part',
      'vname' => 'LBL_SALE_COST_FOR_A_HUNDRED_PART',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'sale_cost_for_a_hundred_part_i' => 
    array (
      'required' => false,
      'name' => 'sale_cost_for_a_hundred_part_i',
      'vname' => 'LBL_SALE_COST_FOR_A_HUNDRED_PART_I',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'cost_of_sale_of_obj_entirely' => 
    array (
      'required' => false,
      'name' => 'cost_of_sale_of_obj_entirely',
      'vname' => 'LBL_COST_OF_SALE_OF_OBJ_ENTIRELY',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'cost_of_sale_of_obj_entirely_i' => 
    array (
      'required' => false,
      'name' => 'cost_of_sale_of_obj_entirely_i',
      'vname' => 'LBL_COST_OF_SALE_OF_OBJ_ENTIRELY_I',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'the_vat' => 
    array (
      'required' => false,
      'name' => 'the_vat',
      'vname' => 'LBL_THE_VAT',
      'type' => 'float',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '18',
      'precision' => '0',
    ),
    'sale_currency' => 
    array (
      'required' => false,
      'name' => 'sale_currency',
      'vname' => 'LBL_SALE_CURRENCY ',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'cost_currency_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'rent_currency' => 
    array (
      'required' => false,
      'name' => 'rent_currency',
      'vname' => 'LBL_RENT_CURRENCY',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'cost_currency_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'c_u_equally_2' => 
    array (
      'required' => false,
      'name' => 'c_u_equally_2',
      'vname' => 'LBL_C_U_EQUALLY_2',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'rent_cost_for_sq_m_a_month' => 
    array (
      'required' => false,
      'name' => 'rent_cost_for_sq_m_a_month',
      'vname' => 'LBL_RENT_COST_FOR_SQ_M_A_MONTH',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'rent_cost_for_sq_m_a_year' => 
    array (
      'required' => false,
      'name' => 'rent_cost_for_sq_m_a_year',
      'vname' => 'LBL_RENT_COST_FOR_SQ_M_A_YEAR',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'rent_c_in_month_of_obj_entirel' => 
    array (
      'required' => false,
      'name' => 'rent_c_in_month_of_obj_entirel',
      'vname' => 'LBL_RENT_C_IN_MONTH_OF_OBJ_ENTIREL',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'rent_c_in_year_of_obj_entirely' => 
    array (
      'required' => false,
      'name' => 'rent_c_in_year_of_obj_entirely',
      'vname' => 'LBL_RENT_C_IN_YEAR_OF_OBJ_ENTIRELY',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'rent_c_for_sq_m_month_rbl' => 
    array (
      'required' => false,
      'name' => 'rent_c_for_sq_m_month_rbl',
      'vname' => 'LBL_RENT_C_FOR_SQ_M_MONTH_RBL',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'rent_c_for_sq_m_year_rbl' => 
    array (
      'required' => false,
      'name' => 'rent_c_for_sq_m_year_rbl',
      'vname' => 'LBL_RENT_C_FOR_SQ_M_YEAR_RBL',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'rent_c_in_month_of_obj_en_rbl' => 
    array (
      'required' => false,
      'name' => 'rent_c_in_month_of_obj_en_rbl',
      'vname' => 'LBL_RENT_C_IN_MONTH_OF_OBJ_EN_RBL',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'rent_c_in_year_of_obj_en_rbl' => 
    array (
      'required' => false,
      'name' => 'rent_c_in_year_of_obj_en_rbl',
      'vname' => 'LBL_RENT_C_IN_YEAR_OF_OBJ_EN_RBL',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'the_vat_2' => 
    array (
      'required' => false,
      'name' => 'the_vat_2',
      'vname' => 'LBL_THE_VAT_2',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'operational_payments' => 
    array (
      'required' => false,
      'name' => 'operational_payments',
      'vname' => 'LBL_OPERATIONAL_PAYMENTS',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'working_costs' => 
    array (
      'required' => '1',
      'name' => 'working_costs',
      'vname' => 'LBL_WORKING_COSTS',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'payment_of_comm_to_intermediar' => 
    array (
      'required' => false,
      'name' => 'payment_of_comm_to_intermediar',
      'vname' => 'LBL_PAYMENT_OF_COMM_TO_INTERMEDIAR',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'the_exclusive_right_on_realisa' => 
    array (
      'required' => false,
      'name' => 'the_exclusive_right_on_realisa',
      'vname' => 'LBL_THE_EXCLUSIVE_RIGHT_ON_REALISA',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'the_comment' => 
    array (
      'required' => false,
      'name' => 'the_comment',
      'vname' => 'LBL_THE_COMMENT',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '200',
    ),
    'total_area_of_a_premise' => 
    array (
      'required' => '1',
      'name' => 'total_area_of_a_premise',
      'vname' => 'LBL_TOTAL_AREA_OF_A_PREMISE',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'the_site_area_in_hundred_parts' => 
    array (
      'required' => '1',
      'name' => 'the_site_area_in_hundred_parts',
      'vname' => 'LBL_THE_SITE_AREA_IN_HUNDRED_PARTS',
      'type' => 'float',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '18',
      'precision' => '0',
    ),
    'the_additional_info_on_area' => 
    array (
      'required' => false,
      'name' => 'the_additional_info_on_area',
      'vname' => 'LBL_THE_ADDITIONAL_INFO_ON_AREA',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '25',
    ),
    'quantity_of_rooms' => 
    array (
      'required' => '1',
      'name' => 'quantity_of_rooms',
      'vname' => 'LBL_QUANTITY_OF_ROOMS',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'quantity_of_bedrooms' => 
    array (
      'required' => '1',
      'name' => 'quantity_of_bedrooms',
      'vname' => 'LBL_QUANTITY_OF_BEDROOMS',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'floor' => 
    array (
      'required' => '1',
      'name' => 'floor',
      'vname' => 'LBL_FLOOR',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'floor_buildings_quantity_of_le' => 
    array (
      'required' => '1',
      'name' => 'floor_buildings_quantity_of_le',
      'vname' => 'LBL_FLOOR_BUILDINGS_QUANTITY_OF_LE',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'kind_from_windows' => 
    array (
      'required' => '1',
      'name' => 'kind_from_windows',
      'vname' => 'LBL_KIND_FROM_WINDOWS',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '25',
    ),
    'quantity_of_apartments_in_the_' => 
    array (
      'required' => '1',
      'name' => 'quantity_of_apartments_in_the_',
      'vname' => 'LBL_QUANTITY_OF_APARTMENTS_IN_THE_',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'quantity_of_apartments_on_a_fl' => 
    array (
      'required' => '1',
      'name' => 'quantity_of_apartments_on_a_fl',
      'vname' => 'LBL_QUANTITY_OF_APARTMENTS_ON_A_FL',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'quantity_of_houses_in_settleme' => 
    array (
      'required' => '1',
      'name' => 'quantity_of_houses_in_settleme',
      'vname' => 'LBL_QUANTITY_OF_HOUSES_IN_SETTLEME',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'building_stage' => 
    array (
      'required' => '1',
      'name' => 'building_stage',
      'vname' => 'LBL_BUILDING_STAGE',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'building_stage_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'building_date_started' => 
    array (
      'required' => '1',
      'name' => 'building_date_started',
      'vname' => 'LBL_BUILDING_DATE_STARTED',
      'type' => 'date',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
    ),
    'date_closed_of_building_year_o' => 
    array (
      'required' => '1',
      'name' => 'date_closed_of_building_year_o',
      'vname' => 'LBL_DATE_CLOSED_OF_BUILDING_YEAR_O',
      'type' => 'date',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
    ),
    'furnish_condition' => 
    array (
      'required' => '1',
      'name' => 'furnish_condition',
      'vname' => 'LBL_FURNISH_CONDITION',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'furnish_condition_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'quality_of_furnish' => 
    array (
      'required' => false,
      'name' => 'quality_of_furnish',
      'vname' => 'LBL_QUALITY_OF_FURNISH',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'quality_of_furnish_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'lay_out' => 
    array (
      'required' => false,
      'name' => 'lay_out',
      'vname' => 'LBL_LAY_OUT',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'lay_out_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'the_description_of_1st_floor' => 
    array (
      'required' => false,
      'name' => 'the_description_of_1st_floor',
      'vname' => 'LBL_THE_DESCRIPTION_OF_1ST_FLOOR',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '100',
    ),
    'the_description_of_2nd_floor' => 
    array (
      'required' => false,
      'name' => 'the_description_of_2nd_floor',
      'vname' => 'LBL_THE_DESCRIPTION_OF_2ND_FLOOR',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '100',
    ),
    'the_description_of_3rd_floor' => 
    array (
      'required' => false,
      'name' => 'the_description_of_3rd_floor',
      'vname' => 'LBL_THE_DESCRIPTION_OF_3RD_FLOOR',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '100',
    ),
    'the_description_of_4th_floor' => 
    array (
      'required' => false,
      'name' => 'the_description_of_4th_floor',
      'vname' => 'LBL_THE_DESCRIPTION_OF_4TH_FLOOR',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '100',
    ),
    'the_description_of_5th_floor' => 
    array (
      'required' => false,
      'name' => 'the_description_of_5th_floor',
      'vname' => 'LBL_THE_DESCRIPTION_OF_5TH_FLOOR',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '100',
    ),
    'material_of_external_walls' => 
    array (
      'required' => '1',
      'name' => 'material_of_external_walls',
      'vname' => 'LBL_MATERIAL_OF_EXTERNAL_WALLS',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'material_of_external_walls_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'windows' => 
    array (
      'required' => '1',
      'name' => 'windows',
      'vname' => 'LBL_WINDOWS',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'windows_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'roof' => 
    array (
      'required' => '1',
      'name' => 'roof',
      'vname' => 'LBL_ROOF',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'roof_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'height_of_ceilings' => 
    array (
      'required' => '1',
      'name' => 'height_of_ceilings',
      'vname' => 'LBL_HEIGHT_OF_CEILINGS',
      'type' => 'float',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '18',
      'precision' => '0',
    ),
    'presence_of_balconies' => 
    array (
      'required' => false,
      'name' => 'presence_of_balconies',
      'vname' => 'LBL_PRESENCE_OF_BALCONIES',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'quantity_of_entrance_groups' => 
    array (
      'required' => false,
      'name' => 'quantity_of_entrance_groups',
      'vname' => 'LBL_QUANTITY_OF_ENTRANCE_GROUPS',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'terrace_presence' => 
    array (
      'required' => false,
      'name' => 'terrace_presence',
      'vname' => 'LBL_TERRACE_PRESENCE',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'the_area_of_a_terrace' => 
    array (
      'required' => false,
      'name' => 'the_area_of_a_terrace',
      'vname' => 'LBL_THE_AREA_OF_A_TERRACE',
      'type' => 'float',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '18',
      'precision' => '0',
    ),
    'presence_of_the_separate_lift' => 
    array (
      'required' => false,
      'name' => 'presence_of_the_separate_lift',
      'vname' => 'LBL_PRESENCE_OF_THE_SEPARATE_LIFT',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'step_of_columns' => 
    array (
      'required' => false,
      'name' => 'step_of_columns',
      'vname' => 'LBL_STEP_OF_COLUMNS',
      'type' => 'float',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '18',
      'precision' => '0',
    ),
    'loading_on_one_sq_m' => 
    array (
      'required' => false,
      'name' => 'loading_on_one_sq_m',
      'vname' => 'LBL_LOADING_ON_ONE_SQ_M',
      'type' => 'float',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '18',
      'precision' => '0',
    ),
    'comments_3' => 
    array (
      'required' => false,
      'name' => 'comments_3',
      'vname' => 'LBL_COMMENTS_3',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '25',
    ),
    'the_site_form' => 
    array (
      'required' => '1',
      'name' => 'the_site_form',
      'vname' => 'LBL_THE_SITE_FORM',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'the_site_form_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'site_protection' => 
    array (
      'required' => '1',
      'name' => 'site_protection',
      'vname' => 'LBL_SITE_PROTECTION',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'site_protection_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'affinity_to_water' => 
    array (
      'required' => '1',
      'name' => 'affinity_to_water',
      'vname' => 'LBL_AFFINITY_TO_WATER',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'affinity_to_water_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'presence_of_affinity_of_wood' => 
    array (
      'required' => '1',
      'name' => 'presence_of_affinity_of_wood',
      'vname' => 'LBL_PRESENCE_OF_AFFINITY_OF_WOOD',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'presence_of_affinity_of_wood_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'the_note' => 
    array (
      'required' => false,
      'name' => 'the_note',
      'vname' => 'LBL_THE_NOTE',
      'type' => 'text',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'studio' => 'visible',
    ),
    'operation_service' => 
    array (
      'required' => false,
      'name' => 'operation_service',
      'vname' => 'LBL_OPERATION_SERVICE',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'presence_territorie' => 
    array (
      'required' => false,
      'name' => 'presence_territorie',
      'vname' => 'LBL_PRESENCE_TERRITORIE',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'object_infrastructure' => 
    array (
      'required' => '1',
      'name' => 'object_infrastructure',
      'vname' => 'LBL_OBJECT_INFRASTRUCTURE',
      'type' => 'text',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'studio' => 'visible',
    ),
    'area_infrastructure' => 
    array (
      'required' => '1',
      'name' => 'area_infrastructure',
      'vname' => 'LBL_AREA_INFRASTRUCTURE',
      'type' => 'text',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'studio' => 'visible',
    ),
    'garage' => 
    array (
      'required' => '1',
      'name' => 'garage',
      'vname' => 'LBL_GARAGE',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'garage_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'car_wash' => 
    array (
      'required' => '1',
      'name' => 'car_wash',
      'vname' => 'LBL_CAR_WASH',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'car_wash_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'parking' => 
    array (
      'required' => '1',
      'name' => 'parking',
      'vname' => 'LBL_PARKING',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'parking_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'quantity_of_parking_spaces' => 
    array (
      'required' => false,
      'name' => 'quantity_of_parking_spaces',
      'vname' => 'LBL_QUANTITY_OF_PARKING_SPACES',
      'type' => 'int',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '11',
      'disable_num_format' => '',
    ),
    'parking_cost' => 
    array (
      'required' => false,
      'name' => 'parking_cost',
      'vname' => 'LBL_PARKING_COST',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
    'currency_3' => 
    array (
      'required' => false,
      'name' => 'currency_3',
      'vname' => 'LBL_CURRENCY_3',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'cost_currency_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'the_comment_to_a_parking' => 
    array (
      'required' => false,
      'name' => 'the_comment_to_a_parking',
      'vname' => 'LBL_THE_COMMENT_TO_A_PARKING',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '100',
    ),
    'protection_presence' => 
    array (
      'required' => false,
      'name' => 'protection_presence',
      'vname' => 'LBL_PROTECTION_PRESENCE',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'check_point' => 
    array (
      'required' => false,
      'name' => 'check_point',
      'vname' => 'LBL_CHECK_POINT',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'the_militarised' => 
    array (
      'required' => false,
      'name' => 'the_militarised',
      'vname' => 'LBL_THE_MILITARISED',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'protection_on_perimetre' => 
    array (
      'required' => false,
      'name' => 'protection_on_perimetre',
      'vname' => 'LBL_PROTECTION_ON_PERIMETRE',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'video_observation' => 
    array (
      'required' => false,
      'name' => 'video_observation',
      'vname' => 'LBL_VIDEO_OBSERVATION',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'another' => 
    array (
      'required' => false,
      'name' => 'another',
      'vname' => 'LBL_ANOTHER',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '200',
    ),
    'electrical_supply' => 
    array (
      'required' => '1',
      'name' => 'electrical_supply',
      'vname' => 'LBL_ELECTRICAL_SUPPLY',
      'type' => 'float',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '18',
      'precision' => '0',
    ),
    'water_supply' => 
    array (
      'required' => '1',
      'name' => 'water_supply',
      'vname' => 'LBL_WATER_SUPPLY',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'water_supply_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'the_water_drain' => 
    array (
      'required' => '1',
      'name' => 'the_water_drain',
      'vname' => 'LBL_THE_WATER_DRAIN',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'the_water_drain_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'heating' => 
    array (
      'required' => '1',
      'name' => 'heating',
      'vname' => 'LBL_HEATING',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '7',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'heating_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'gas_supply' => 
    array (
      'required' => '1',
      'name' => 'gas_supply',
      'vname' => 'LBL_GAS_SUPPLY',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'gas_supply_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'water_filtration' => 
    array (
      'required' => false,
      'name' => 'water_filtration',
      'vname' => 'LBL_WATER_FILTRATION',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'water_filtration_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'ventilation_and_air_conditioni' => 
    array (
      'required' => '1',
      'name' => 'ventilation_and_air_conditioni',
      'vname' => 'LBL_VENTILATION_AND_AIR_CONDITIONI',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'ventilation_and_air_conditioni_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'presence_of_lifts' => 
    array (
      'required' => false,
      'name' => 'presence_of_lifts',
      'vname' => 'LBL_PRESENCE_OF_LIFTS',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'electroconducting_material' => 
    array (
      'required' => false,
      'name' => 'electroconducting_material',
      'vname' => 'LBL_ELECTROCONDUCTING_MATERIAL',
      'type' => 'enum',
      'massupdate' => 0,
      'default' => '1',
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'electroconducting_material_list',
      'studio' => 'visible',
      'dependency' => false,
    ),
    'additional_data' => 
    array (
      'required' => false,
      'name' => 'additional_data',
      'vname' => 'LBL_ADDITIONAL_DATA',
      'type' => 'text',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'studio' => 'visible',
    ),
    'telephone_line' => 
    array (
      'required' => false,
      'name' => 'telephone_line',
      'vname' => 'LBL_TELEPHONE_LINE',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'the_internet' => 
    array (
      'required' => false,
      'name' => 'the_internet',
      'vname' => 'LBL_THE_INTERNET',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'cable_television' => 
    array (
      'required' => false,
      'name' => 'cable_television',
      'vname' => 'LBL_CABLE_TELEVISION',
      'type' => 'bool',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '255',
    ),
    'variant_1' => 
    array (
      'required' => false,
      'name' => 'variant_1',
      'vname' => 'LBL_VARIANT_1',
      'type' => 'multienum',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'variant_1_list',
      'studio' => 'visible',
      'isMultiSelect' => true,
    ),
    'variant_2' => 
    array (
      'required' => false,
      'name' => 'variant_2',
      'vname' => 'LBL_VARIANT_2',
      'type' => 'multienum',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'variant_2_list',
      'studio' => 'visible',
      'isMultiSelect' => true,
    ),
    'documents_of_the_physical_pers' => 
    array (
      'required' => false,
      'name' => 'documents_of_the_physical_pers',
      'vname' => 'LBL_DOCUMENTS_OF_THE_PHYSICAL_PERS',
      'type' => 'multienum',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => 0,
      'audited' => 0,
      'reportable' => 0,
      'len' => 100,
      'options' => 'documents_of_the_physical_pers_list',
      'studio' => 'visible',
      'isMultiSelect' => true,
    ),
    'id_object' => 
    array (
      'required' => false,
      'name' => 'id_object',
      'vname' => 'LBL_ID_OBJECT',
      'type' => 'varchar',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => '25',
    ),
    'parking_cost_rbl' => 
    array (
      'required' => false,
      'name' => 'parking_cost_rbl',
      'vname' => 'LBL_PARKING_COST_RBL',
      'type' => 'currency',
      'massupdate' => 0,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => 0,
      'reportable' => 0,
      'len' => 26,
    ),
  ),
  'relationships' => 
  array (
  ),
);
?>
